import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import { Suspense } from "react";
import { Toaster } from "@/component/ui/toaster";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { AuthProvider } from "./context/authContext";
import MyApp from "./_app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <MyApp>
          {children}
        </MyApp>
      </body>
    </html>
  );
}
